# -*- coding: utf-8 -*-
"""Clean_car_Spec_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFjt2uqnNbhbJyItul7GsvdRJ0V1pAoo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data from the uploaded file
file_path = 'Car_Spec_Data_csv.csv'
df = pd.read_csv(file_path)

# Generate summary statistics
summary_stats = df.describe()

# Save summary statistics to a text file
with open('summary.txt', 'w') as f:
    f.write(summary_stats.to_string())

# Save summary statistics to a markdown file
summary_stats_md = summary_stats.to_markdown()
with open('summary.md', 'w') as f:
    f.write("# Summary Statistics\n\n")
    f.write(summary_stats_md)

# Print summary statistics to the console
print(summary_stats)

# Calculate the number of null values in each column
null_counts = df.isnull().sum()

# Create a bar plot for null values
plt.figure(figsize=(12, 8))
bar_plot = sns.barplot(x=null_counts.index, y=null_counts.values, palette='viridis')
plt.title('Number of Null Values in Each Column')
plt.xlabel('Columns')
plt.ylabel('Number of Null Values')
plt.xticks(rotation=90)

# Add values on top of the bars
for p in bar_plot.patches:
    bar_plot.annotate(format(p.get_height(), '.0f'),
                      (p.get_x() + p.get_width() / 2., p.get_height()),
                      ha='center', va='center',
                      xytext=(0, 10),
                      textcoords='offset points')

# Remove plot borders
sns.despine()

# Save the plot
plt.savefig('null_values_plot.png')

# Append the plot to the markdown file
with open('summary.md', 'a') as f:
    f.write("\n\n# Null Values Plot\n\n")
    f.write("![Null Values Plot](null_values_plot.png)")

# Show the plot
plt.show()

# Bar plot for categorical variable 'Car_Body'
plt.figure(figsize=(15, 6))
sns.countplot(data=df, x='Car_Body')
plt.title('Distribution of Car Body Types')
plt.xlabel('Car Body Type')
plt.ylabel('Count')
sns.despine()
plt.show()

# Heatmap for missing values
plt.figure(figsize=(12, 8))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Heatmap of Missing Values')
plt.show()
