# -*- coding: utf-8 -*-
"""Clean_car_Spec_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFjt2uqnNbhbJyItul7GsvdRJ0V1pAoo
"""

import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data from the uploaded file
file_path = '/content/Car_Spec_Data_csv.csv'
df = pd.read_csv(file_path)

# Generate summary statistics
summary_stats = df.describe()
summary_stats

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the number of null values in each column
null_counts = df.isnull().sum()

# Create a bar plot for null values
plt.figure(figsize=(12, 8))
bar_plot = sns.barplot(x=null_counts.index, y=null_counts.values, palette='viridis')
plt.title('Number of Null Values in Each Column')
plt.xlabel('Columns')
plt.ylabel('Number of Null Values')
plt.xticks(rotation=90)

# Add values on top of the bars
for p in bar_plot.patches:
    bar_plot.annotate(format(p.get_height(), '.0f'),
                      (p.get_x() + p.get_width() / 2., p.get_height()),
                      ha = 'center', va = 'center',
                      xytext = (0, 10),
                      textcoords = 'offset points')

# Remove plot borders
sns.despine()

plt.show()

# Bar plot for categorical variable 'Car_Body'
plt.figure(figsize=(15, 6))
sns.countplot(data=df, x='Car_Body')
plt.title('Distribution of Car Body Types')
plt.xlabel('Car Body Type')
plt.ylabel('Count')
sns.despine()
plt.show()


# Box plot for 'Battery (kWh)' by 'Car_Body'
plt.figure(figsize=(12, 6))
sns.boxplot(x='Car_Body', y='Battery (kWh)', data=df)
plt.title('Battery (kWh) by Car Body Type')
plt.xlabel('Car Body Type')
plt.ylabel('Battery (kWh)')
plt.xticks(rotation=90)
sns.despine()
plt.show()

# Histogram for 'Battery (kWh)'
plt.figure(figsize=(10, 6))
sns.histplot(df['Battery (kWh)'].dropna(), bins=30, kde=True)
plt.title('Distribution of Battery (kWh)')
plt.xlabel('Battery (kWh)')
plt.ylabel('Frequency')
sns.despine()
plt.show()

# Heatmap for missing values
plt.figure(figsize=(12, 8))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Heatmap of Missing Values')
plt.show()