# -*- coding: utf-8 -*-
"""Clean_car_Spec_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFjt2uqnNbhbJyItul7GsvdRJ0V1pAoo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data from the uploaded file
file_path = 'Car_Spec_Data_csv.csv'
df = pd.read_csv(file_path)

# Calculate the number of null values in each column
null_counts = df.isnull().sum()

# Create a bar plot for null values
plt.figure(figsize=(12, 8))
bar_plot = sns.barplot(x=null_counts.index, y=null_counts.values, hue=null_counts.index, legend=False, palette='viridis')
plt.title('Number of Null Values in Each Column')
plt.xlabel('Columns')
plt.ylabel('Number of Null Values')
plt.xticks(rotation=90)

# Add values on top of the bars
for p in bar_plot.patches:
    bar_plot.annotate(format(p.get_height(), '.0f'),
                      (p.get_x() + p.get_width() / 2., p.get_height()),
                      ha='center', va='center',
                      xytext=(0, 10),
                      textcoords='offset points')

# Remove plot borders
sns.despine()

# Save the plot
plt.savefig('null_values_plot.png')

# Show the plot
plt.show()
