name: spec-data
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install CML
        run: |
          npm install -g @dvcorg/cml

      - name: Run Data Cleaning Script
        run: |
          python clean_car_spec_data.py

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Generate the CML report
          echo "# Null Values Plot" >> report.md
          cml-publish null_values_plot.png --md >> report.md
          cml-send-comment report.md
