name: spec-data
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: run script
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          pip install -r requirements.txt
          python clean_car_spec_data.py

          echo "## Null Value Count" >report.md
          echo "![](./null_values_plot.png)" >> report.md
          cml comment create report.md
