name: spec-data
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install CML
        run: |
          npm install -g @dvcorg/cml

      - name: Run Data Cleaning Script
        run: |
          python clean_car_spec_data.py

      - name: Display Summary Stats
        run: |
          echo "summary_stats"
          cat summary.txt

      - name: Upload Plot and Summary
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: |
            null_values_plot.png
            summary.md

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cml comment create summary.md --token ${{ secrets.REPO_TOKEN }}
