name: spec-data
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Cleaning Script
        run: |
          python clean_car_spec_data.py

      - name: Upload Plot
        uses: actions/upload-artifact@v2
        with:
          name: null-values-plot
          path: null_values_plot.png

      - name: Get Artifact URL
        id: get-url
        run: |
          echo "artifact_url=https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/${{ steps.upload.outputs.artifact_id }}/null-values-plot.png" >> $GITHUB_ENV

      - name: Create Comment with Plot
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request ? context.payload.pull_request.number : context.payload.issue.number;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `# Null Values Plot\n\n![Null Values Plot](${{ env.artifact_url }})`
            });
